function themesLogic() {
  const generators = (window as any).SinkarGenerators;

  return {
    repoName:
      (window as any).repoName || localStorage.getItem("sinkar.repoName") || "",
    selectedTheme: "writer",
    loading: false,
    status: "",
    
    // Configuration State
    config: {
      siteTitle: "My Awesome Site",
      siteDescription: "A static site generated by Sinkar",
      paletteId: "default",
      fontFamily: "system-ui, -apple-system, sans-serif",
      borderRadius: "8px",
      layoutStyle: "default",
      designVariant: "default",
      extraPages: []
    } as any,

    palettes: generators.PALETTES,

    themes: [
      { id: "writer", name: "Modern Writer (Blog)" },
      { id: "portfolio", name: "Creative Portfolio" },
      { id: "store", name: "Digital Storefront" },
      { id: "landing", name: "SaaS Landing Page" },
    ],

    init() {
      window.addEventListener("workspace:mounted", () => {
        this.repoName = localStorage.getItem("sinkar.repoName") || "";
        if (this.repoName) {
          this.loadConfig();
        }
      });
      
      // Listen for repo updates to regenerate script.js with fresh articles
      window.addEventListener("repo:files-updated", (e: any) => {
        const { repoName } = e.detail || {};
        if (repoName && repoName === this.repoName) {
            this.updateSiteScript();
        }
      });

      // Also try loading if repoName is already set (e.g. on refresh)
      if (this.repoName) {
        this.loadConfig();
      }
    },

    async updateSiteScript() {
        if (!this.repoName) return;
        console.log("Regenerating site script...");
        try {
            // 1. Read articles.json
            let articlesData = [];
            try {
                const jsonContent = await (window as any).git.readSiteFile(this.repoName, "articles.json");
                if (jsonContent) {
                    articlesData = JSON.parse(jsonContent);
                }
            } catch (e) {
                console.warn("Could not read articles.json for injection", e);
            }

            // 2. Generate JS with current config and new articles
            // Ensure config is loaded
            if (!this.config.siteTitle) await this.loadConfig();
            
            const js = generators.generateJs(this.config, this.selectedTheme, articlesData);
            await (window as any).git.writeSiteFile(this.repoName, "swp/script.js", js);
            console.log("Site script updated with new articles.");
        } catch (e) {
            console.error("Failed to update site script", e);
        }
    },

    async loadConfig() {
      if (!this.repoName) return;
      try {
        const content = await (window as any).git.readSiteFile(this.repoName, "swp/theme-config.json");
        if (content && typeof content === 'string') {
          const savedConfig = JSON.parse(content);
          // Merge saved config with default structure to ensure all fields exist
          this.config = { ...this.config, ...savedConfig };
          if (savedConfig.themeId) {
            this.selectedTheme = savedConfig.themeId;
          }
        }
      } catch (e) {
        console.log("No existing config found or error loading it", e);
      }
    },

    async applyTheme() {
      if (!this.repoName) {
        this.status = "No repository selected.";
        return;
      }
      this.loading = true;
      this.status = "Applying theme...";

      try {
        // 0. Save Config
        const configToSave = {
          ...this.config,
          themeId: this.selectedTheme,
          updatedAt: new Date().toISOString()
        };
        await (window as any).git.writeSiteFile(this.repoName, "swp/theme-config.json", JSON.stringify(configToSave, null, 2));

        // 1. Generate index.html
        const indexHtml = generators.generateHtml(this.config, this.selectedTheme);
        await (window as any).git.writeSiteFile(this.repoName, "index.html", indexHtml);

        // 2. Rebuild articles.json first so we have fresh data
        const indexMsg = await (window as any).git.rebuildIndex(this.repoName);

        // 3. Read the rebuilt articles.json to inject into JS
        let articlesData = [];
        try {
            const jsonContent = await (window as any).git.readSiteFile(this.repoName, "articles.json");
            if (jsonContent) {
                articlesData = JSON.parse(jsonContent);
            }
        } catch (e) {
            console.warn("Could not read articles.json for injection", e);
        }

        // 4. Generate swp/ files (CSS, JS)
        const css = generators.generateCss(this.config, this.selectedTheme);
        await (window as any).git.writeSiteFile(this.repoName, "swp/style.css", css);
        
        // Pass articlesData to generateJs to inline them
        const js = generators.generateJs(this.config, this.selectedTheme, articlesData);
        await (window as any).git.writeSiteFile(this.repoName, "swp/script.js", js);

        this.status = `Theme '${this.selectedTheme}' applied! ${indexMsg}. Push to publish.`;
        
        // Notify other components that theme has changed
        window.dispatchEvent(new Event('theme:changed'));
      } catch (e: any) {
        this.status = "Error: " + e.message;
      } finally {
        this.loading = false;
      }
    },
  };
}

(window as any).themesLogic = themesLogic;

const initThemes = async () => {
  try {
    const res = await fetch("components/themes.html");
    if (!res.ok) return;
    const html = await res.text();
    const wrapper = document.createElement("div");
    wrapper.innerHTML = html;
    document.body.appendChild(wrapper);
  } catch {}
};

window.addEventListener("workspace:mounted", initThemes);
